### ISSUE TITLE
ERR_STRING_TOO_LONG from buffer.js when using API=bitcoin-node

### ISSUE THREAD

**Issue by mboyd1** [runonbitcoin/run-db#12]
Trying to sync a run-db instance on mainnet from a local node, using `API=bitcoin-node` and hit repeatable failure:

`buffer.js:799
    return this.utf8Slice(start, end);`

`Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:799:17)
    at IncomingMessage.handleStreamEnd (/run-db/node_modules/axios/lib/adapters/http.js:253:41)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STRING_TOO_LONG'
}`

**Comment by mboyd1** [comment]
seems to be fixed in [3123350](https://github.com/runonbitcoin/run-db/commit/3123350b6f93dfdef6e923cf0fd1a5eaed2e2f2f)
I'm now synced on mainnet from local node
